### ISSUE TITLE
Build re2 failed in Mac OS X

### ISSUE THREAD

**Issue by chinhniem80** [tuncer/re2#19] opened 2017-02-28 10:28 UTC
after extracting the source, go to re2-master  folder and 'make':
==> re2-master (compile)
Cloning into 're2'...
fatal: remote error: 

Invalid authentication credentials.

Please generate a new identifier:
  https://code.googlesource.com/new-password

ERROR: Command [compile] failed!
make: *** [all] Error 1
==============
Any help,
Thank you.

**Comment by tuncer** [comment] 2017-02-28 20:08
Unfortunately, like @michalwski, I cannot reproduce this. Can you try in a different user environment, to be sure there's no user config that causes this?

I also have no problem cloning a random code.googlesource.com repository: `git clone https://code.googlesource.com/elt`

@junyer, any idea?

**Comment by junyer** [comment] 2017-03-05 11:39
Check `.gitconfig` to see where `http.cookiefile` points, then check that for `googlesource.com` entries. You should find one or two, presumably, which you can either regenerate (as instructed previously) or remove.

**Comment by tuncer** [comment] 2017-03-13 22:01
@chinhniem80, did @junyer's explanation help resolve the issue?

**Comment by chinhniem80** [comment] 2017-03-14 02:00
No, I did not continue installing it in Mac OS more. 
But I tried to do it in Unix. And it had the same issue. But the issue does not come from google credential... It was a quite different thing. 
For building re2, need to update gcc/g++ to 4.9 (it does not work in ver 4.7) :
Try to do the same in Mac OS:
1.  apt-get install build-essential
2.  add-apt-repository ppa:ubuntu-toolchain-r/test
3.  apt-get update
4.  apt-get install gcc-4.9 g++-4.9 cpp-4.9
5.  cd /usr/bin
6.  rm gcc g++ cpp
7.  ln -s gcc-4.9 gcc
8.  ln -s g++-4.9 g++
9.  ln -s cpp-4.9 cpp

After that, you can check the gcc/g++ version:
  g++ --version:
the result like this:
		 g++ (Ubuntu 4.9.4-2ubuntu1~12.04) 4.9.4
		 Copyright (C) 2015 Free Software Foundation, Inc.
		 This is free software; see the source for copying conditions.  There is NO
		 warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

After all, go to re2 folder and make, it worked in my case.

**Comment by tuncer** [comment] 2017-03-14 03:29
I don't know if those are the usual steps to upgrade the system wide gcc toolchain on Ubuntu, or if there's another (i.e. automated) way, but I think you forgot to update the `cc` and `c++` commands. That said, gcc 4.8 should be sufficient, if that's easier to install than 4.9 (or 6.x).

**Comment by tuncer** [comment] 2017-03-19 22:36
@chinhniem80, did it work after updating `c++` and `cc`? If not, you can also override the C++ compiler via the `$CXX` env var.

**Comment by chinhniem80** [comment] 2017-03-20 02:35
It worked for me as I said.

**Comment by tuncer** [comment] 2017-04-02 20:16
Please try again in your macOS environment, following @junyer's explanation regarding googlecode git auth tokens.

Unless I'm missing something, there's no bug in the build scripts and it has just been a local git client issue.

**Comment by tuncer** [comment] 2017-04-09 20:55
As a side effect of df0eb14a32635085f878ac3d42c8a125faec54ed this is void. Closing.

**Closed by tuncer** 2017-04-09 20:55 UTC
