### ISSUE TITLE
erl_nif.h: No such file or directory

### ISSUE THREAD

**Issue by hopewise** [tuncer/re2#16] opened 2016-09-18 06:36 UTC
Can you please advice how to solve this error:

> # mix deps.compile re2
> ==> re2 (compile)
> Compiling c_src/re2_nif.cpp
> c_src/re2_nif.cpp:5:21: fatal error: erl_nif.h: No such file or directory
>  #include "erl_nif.h"
>                      ^
> compilation terminated.
> ERROR: compile failed while processing /tmp/edeliver/myapp/builds/deps/re2: rebar_abort
> ** (Mix) Could not compile dependency :re2, "/root/.mix/rebar" command failed. You can recompile this dependency with "mix deps.compile re2", update it with "mix deps.update re2" or clean it with "mix deps.clean re2"

I got this error when I try to deploy my elixir app using edeliver, I am on:

```
# elixir -v
Erlang/OTP 19 [erts-8.0] [source] [64-bit] [smp:2:2] [async-threads:10] [kernel-poll:false]

Elixir 1.3.2

```

**Comment by tuncer** [comment] 2016-09-18 11:35
Is it possible that your Erlang installation doesn't have `erl_nif.h`?

```
$ file $(erl -noshell -eval 'io:format("~s~n", [filename:join([lists:concat([code:root_dir(), "/erts-", erlang:system_info(version)]), "include", "erl_nif.h"])]), init:stop(0).')
```

It's not the cause of the error you've encountered, but I've modified the include directive to be more correct (https://github.com/tuncer/re2/commit/f29f5d3750710399ae85c769f70bbd7c884c2e7d), because we obviously are not looking for it in `re2/c_src`. The reason it was `"erl_nif.h"` is because it's copied verbatim from the nif documenation (see https://github.com/erlang/otp/pull/1171 for a fix).

**Comment by hopewise** [comment] 2016-09-18 12:22
I am sorry, but what does that 'file' command do? I've tried it, I got a prompt >

**Comment by tuncer** [comment] 2016-09-18 12:43
It runs `file` on `erl_nif.h`, where the path to `erl_nif.h` is retrieved by invoking `erl`, printing the path, and exiting the vm. I don't know why it would start the Erlang shell and wait for input.

Does it make a difference if you run with `-noinput` (which means no shell and no waiting for input) instead `-noshell`?

    erl -noinput -eval 'io:format("~s~n", [filename:join([lists:concat([code:root_dir(), "/erts-", erlang:system_info(version)]), "include", "erl_nif.h"])]), init:stop(0).'

If you still land in a shell, can you run

```
filename:join([lists:concat([code:root_dir(), "/erts-", erlang:system_info(version)]), "include", "erl_nif.h"]).
```

and

```
file:read_file_info(filename:join([lists:concat([code:root_dir(), "/erts-", erlang:system_info(version)]), "include", "erl_nif.h"])).
```

?

**Comment by hopewise** [comment] 2016-09-18 12:47
using `-noinput` I got the path:

    /usr/lib/erlang/erts-8.0/include/erl_nif.h

**Comment by tuncer** [comment] 2016-09-18 12:52
Does that file exist?

**Comment by hopewise** [comment] 2016-09-19 08:39
# cat /usr/lib/erlang/erts-8.0/include/erl_nif.h
    cat: /usr/lib/erlang/erts-8.0/include/erl_nif.h: No such file or directory

**Comment by tuncer** [comment] 2016-09-19 19:44
How did you install Erlang? Is it possible that it's split into multiple distro packages, and there's a `-dev` or `-devel` package you might have to install?

**Comment by hopewise** [comment] 2016-09-20 10:56
I've used a pre-installed elixir at a DigitalOcean one click droplet.. What do you recommend? Maybe an ansible script on a fresh instance?

**Comment by tuncer** [comment] 2016-09-20 12:23
If it's something you can select for your droplet, and you can list the options, maybe I can help you choose one. If not, https://github.com/mtpereira/ansible-erlang looks like it should provide an up to date Erlang installation.

**Comment by tuncer** [comment] 2016-09-20 12:24
You will also need `git` and `c++` to build the NIF lib.

**Comment by tuncer** [comment] 2016-10-01 12:34
Did you resolve the issue?

**Comment by tuncer** [comment] 2016-10-06 19:18
Interpreting no feedback as a sign that it has been resolved. Closing. Feel free to re-open if not.

**Closed by tuncer** 2016-10-06 19:18 UTC

**Comment by sabondano** [comment] 2017-02-24 05:07
Having some trouble compile re2 with elixir 1.4.2. Anything comes to mind? Seems like a similar issue as the above.

```
Compiling /re2/c_src/re2_nif.cpp
/deps/re2/c_src/re2_nif.cpp:8:10: fatal error: 're2/re2.h' file not found
#include <re2/re2.h>
         ^
1 error generated.
```

**Comment by tuncer** [comment] 2017-02-24 23:01
@sabondano, this ticket was about an incomplete Erlang/OTP installation where the NIF C headers and probably other files were missing. The error you see is unrelated, and the path `/re2/c_src/re2_nif.cpp` looks incomplete, as does `/deps/re2/c_src/re2_nif.cpp`. Seeing how `re2_nif.cpp` is actually processed by `CXX`, did you perhaps cut off the prefix before commenting and the real path doesn't look like that? Also, did you by any chance set the env var `SYSTEM_RE2`? If not, does `deps/re2/c_src/re2/re2/re2.h` exist? 

If the problem persists, please open a separate ticket and don't forget to include steps to reproduce. If you can run with a higher verbosity level to log the `CXX` invocation, please do. You can also set the env var `DEBUG_CONFIG=1` for logging the result of re2/rebar.config.script before it's used. That will reveal incorrect `CXXFLAGS` (e.g. `-I<re2_include_dir>`).

**Comment by tuncer** [comment] 2017-02-28 20:10
@sabondano, were you able to resolve the problem?

**Comment by sabondano** [comment] 2017-02-28 21:04
Yes, cleaned all deps and tried from scratch \o/ :) Thank you!
